### ISSUE TITLE
Suggestion: Attribute for declaring required fields

### ISSUE THREAD

**Issue by Fasteroid** [basilisque-framework/AutoImplementer#2]
Unfortunately, C# does not currently allow this syntax:
```cs
public interface IAmSad {
    required int WhyNot
}
```
This means devs can't declare `required` fields on classes using this code generator (yet).  How sad.

However, I bet this limitation could easily be worked around by introducing an attribute that this generator could look for:
```cs
public interface IAmSad {
    [Required] int WhyNot { get; set; }
}
```
 Might PR this too

**Comment by astaerk** [comment]
Yeah, I also thought about that last week.
Will look into your PR. Thank you!
