### ISSUE TITLE
Suggestion: [NonNullableRequired] attribute for interfaces

### ISSUE THREAD

**Issue by Fasteroid** [basilisque-framework/AutoImplementer#7]
Such an attribute would stop devs from needing to declare [Required] on everything in an interface, and instead would allow for a single top-level declaration to mark anything that isn't nullable as required.  It would save me time, at least.

**Comment by astaerk** [comment]
I just added a change that supports this scenario.
You now can specify to implement all properties as required as a parameter on the interface attribute:
```
[Basilisque.AutoImplementer.Annotations.AutoImplementInterface(ImplementAllPropertiesAsRequired = true)]
public interface IMyInterface
{ }
```

I will push a new version to NuGet later

**Comment by Fasteroid** [comment]
ImplementAllPropertiesAsRequired is great, but doesn't exactly fit the use case I was describing in this issue.

Say I have this interface:
```
[AutoImplementInterface(ImplementAllPropertiesAsRequired = true)]
public interface ITest {
    public int RequiredInt { get; set; }
    public int? NullableInt { get; set; }
}
```

It'll actually be implemented like this:
```
public partial class Test {
    public required int RequiredInt { get; set; }
    public required int? NullableInt { get; set; }
}
```

Which is different from the initial idea of "NonNullableRequired".  
Instantiating one of these would be really annoying!
```
new Test() {
    RequiredInt = 1,
    NullableInt = null // duh??? lmao
}
```

Can you please re-open this issue? 😄
